###########################################################
#                       DLIO General                      #
###########################################################

/**:
  ros__parameters:
    version: 1.1.1
    use_sim_time: true
    adaptive: true

    # Debug
    deep_debug/odom: false
    debug/odom: false
    debug/print_odom: true

    # TF source for map->odom: "odom" (OdomNode) or "lio_sam_opt"
    map/tf_source: "odom"

    # Frames
    frames/map: map
    frames/odom: odom
    frames/baselink: base_link
    frames/lidar: lidar
    frames/imu: imu
